export const CROP_MAPPING = {
    Sugarcane: 15,
    Jowar: 6,
    Cotton: 1,
    Rice: 13,
    Wheat: 19,
    Groundnut: 5,
    Maize: 7,
    pigeonpeas: 20,
    Urad: 18,
    Moong: 10,
    Gram: 3,
    Masoor: 8,
    Soybean: 14,
    Ginger: 2,
    Turmeric: 17,
    Grapes: 4,
    Tobacco: 16,
    Barley: 0,
    Millets: 9,
    "Oil seeds": 11,
    Pulses: 12,
};

export const CROP_OPTIONS = [
    "Wheat",
    "Rice",
    "Jowar",
    "Cotton",
    "Groundnut",
    "Millets",
    "Sugarcane",
    "pigeonpeas",
    "Ginger",
    "Oil seeds",
    "Pulses",
    "Barley",
    "Soybean",
    "Tobacco",
    "Gram",
    "Grapes",
    "Turmeric",
    "Moong",
    "Urad",
    "Maize",
];
